### PR TITLE
Fix: CI Workflow

### PR DESCRIPTION
**Pull request by Drish-xD**
#38 Fixed the version of pre-commit/action from v3.0.1 -> v2.0.3

### CODE REVIEW

**Comment by Drish-xD** [comment]
Hey @suryabulusu, Please review the PR.

**Review by suryabulusu — COMMENTED** [review]
hey thanks! can you add DMP 2024 and other things in `.gitignore`? I just approved pre-commit github actions run for this PR and it seems to fail because of issue template. also please do submit a proposal!

**Comment by Drish-xD** [comment]
Okay, will do it by today.

And I submitted the proposal yesterday. 🚀🚀✌️

**Comment by Drish-xD** [comment]
@suryabulusu I have fixed the CI Issue by excluding the Template folder in the `.github/` dir from `trailing-whitespace hook`. 
image

**Review by suryabulusu — APPROVED** [review]
looks good. thanks!

**Pull request merged**
